[package]
name = "buddy_system_allocator"
version = "0.1.0"
authors = ["Jiajie Chen <noc@jiegec.ac.cn>"]
edition = "2018"
license = "MIT"

[features]
default = ["use_spin"]
use_spin = ["spin"]

[dependencies.spin]
version = "0.5"
optional = true